name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4.1.1
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          excluded_paths: ".github,__pycache__,venv,.idea"
